//
// Created by Biruk Abate on 21/08/23.
//

#ifndef FINANCIALTRANSACTIONSYSTEM_TRANSACTION_H
#define FINANCIALTRANSACTIONSYSTEM_TRANSACTION_H

#endif //FINANCIALTRANSACTIONSYSTEM_TRANSACTION_H

#include <string>